name: vyuh_cli
description: A command-line interface for the Vyuh Framework to generate Vyuh projects from predefined templates.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.1
  pub_updater: ^0.5.0
  mason: ^0.1.0-dev.60
  meta: ^1.15.0
  universal_io: ^2.2.2
  path: ^1.9.0
  yaml_edit: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.25.8

executables:
  vyuh:
