name: {{ name.snakeCase() }}
description: {{ description }}


packages:
  - plugins/*
  - features/*
  - features/*/*
  - packages/*
  - apps/*

ide:
  intellij:
    moduleNamePrefix: ''

command:
  version:
    workspaceChangelog: false
